// <auto-generated />
using Lilia.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lilia.Migrations
{
    [DbContext(typeof(LiliaDbContext))]
    [Migration("20210916030907_OsuModelUpdate")]
    partial class OsuModelUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Lilia.Database.Models.DbGuild", b =>
                {
                    b.Property<ulong>("DbGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ranking")
                        .HasColumnType("INTEGER");

                    b.HasKey("DbGuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Lilia.Database.Models.DbUser", b =>
                {
                    b.Property<ulong>("DbUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OsuMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsuUsername")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Shards")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DbUserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
