// <auto-generated />
using System;
using Lilia.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lilia.Migrations
{
    [DbContext(typeof(LiliaDbContext))]
    [Migration("20220201120039_QueueRework")]
    partial class QueueRework
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Lilia.Database.Models.DbGuild", b =>
                {
                    b.Property<ulong>("DbGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordGuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("LastPlayedPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPlayedTrack")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueItem")
                        .HasColumnType("TEXT");

                    b.HasKey("DbGuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Lilia.Database.Models.DbUser", b =>
                {
                    b.Property<ulong>("DbUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsuMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsuUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("DbUserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
