// <auto-generated />
using System;
using Lilia.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lilia.Migrations
{
    [DbContext(typeof(LiliaDatabaseContext))]
    [Migration("20220317041903_AddRadioPlayTime")]
    partial class AddRadioPlayTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.1.22076.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lilia.Database.Models.DbGuild", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GoodbyeChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GoodbyeMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsGoodbyeEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWelcomeEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RadioStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WelcomeChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Lilia.Database.Models.DbUser", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("OsuMode")
                        .HasColumnType("text");

                    b.Property<string>("OsuUsername")
                        .HasColumnType("text");

                    b.Property<short>("WarnCount")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
