// <auto-generated />
using Helya.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helya.Migrations
{
    [DbContext(typeof(HelyaDatabaseContext))]
    [Migration("20220213130343_ANewBeginning")]
    partial class ANewBeginning
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Helya.Database.Models.DbGuild", b =>
                {
                    b.Property<ulong>("DbGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordGuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DbGuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Helya.Database.Models.DbUser", b =>
                {
                    b.Property<ulong>("DbUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsuMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsuUsername")
                        .HasColumnType("TEXT");

                    b.Property<short>("WarnCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("DbUserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
